/* Generated By:JJTree&JavaCC: Do not edit this line. MiniCConstants.java */

/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PlusMinus = 5;
  /** RegularExpression Id. */
  int TermOp = 6;
  /** RegularExpression Id. */
  int Compare = 7;
  /** RegularExpression Id. */
  int TYPE = 8;
  /** RegularExpression Id. */
  int COLON = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int FOR = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int OPENB = 16;
  /** RegularExpression Id. */
  int CLOSEB = 17;
  /** RegularExpression Id. */
  int OPENC = 18;
  /** RegularExpression Id. */
  int CLOSEC = 19;
  /** RegularExpression Id. */
  int INT = 20;
  /** RegularExpression Id. */
  int FLOAT = 21;
  /** RegularExpression Id. */
  int IDENTIFIER = 22;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<PlusMinus>",
    "<TermOp>",
    "<Compare>",
    "<TYPE>",
    "\",\"",
    "\";\"",
    "\"=\"",
    "\"for\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<INT>",
    "<FLOAT>",
    "<IDENTIFIER>",
  };

}
